name: CI Pipeline

on:
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python 3
      run: sudo apt-get update && sudo apt-get install python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  

    - name: Set up environment
      run: echo "NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV

    - name: Run final.py
      run: python final.py

    - name: Configure Git identity
      run: |
        git config user.email "thejaswi.cy@triconinfotech.com"
        git config user.name "thejaswitricon"

    - name: Create Branch and Pull Request
      run: |
        git checkout -b feature-branch # Create a new branch
        git add . && git commit -m "Automatic commit" # Commit changes
        git push origin feature-branch # Push changes to the remote repository

        # Get the last commit message
        commit_message=$(git log --format=%B -n 1)

        # Create a pull request using GitHub API
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title": "'"${commit_message}"'",
            "head": "feature-branch",
            "base": "main"
          }'