name: Update data.csv

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_GITHUB }}
        fetch-depth: 0


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x


    - name: Install Python 3
      run: |
        pip --version
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install requests  

    - name: Set up environment
      run: |
        echo "NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
        echo "NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID}}" >> $GITHUB_ENV

    - name: Run final.py
      run: python ./lib/final.py

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_GITHUB }}
        commit-message: Update data.csv file
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: feature-branch
        delete-branch: true
        title: 'fix(dashboards): update data'
        body: |
          Update report
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]
