name: CI Pipeline

on:
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run final.py
      run: python final.py

    - name: Create Branch and Pull Request
      run: |
        git checkout -b feature-branch # Create a new branch
        git add . && git commit -m "Automatic commit" # Commit changes
        git push origin feature-branch # Push changes to the remote repository

        # Create a pull request using GitHub API
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title": "Automatic Pull Request",
            "head": "feature-branch",
            "base": "main"
          }'
