name: Update data.csv

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_GITHUB }}
        fetch-depth: 0


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python 3
      run: sudo apt-get update && sudo apt-get install python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  
        
    - name: Install tflint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash    

    - name: Set up environment
      run: |
        echo "NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
        echo "NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID}}" >> $GITHUB_ENV

    - name: Run final.py
      run: |
        cd lib
        python final.py

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"


    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_GITHUB }}
        commit-message: Update data.csv file
        committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: fix-update-dashboard-${{ steps.date.outputs.date }}  # Appending date to branch name
        delete-branch: true
        title: 'fix(dashboards): update data'
        
